=== apache/pluto/pluto-portal-driver/src/main/resources/pluto-portal-driver-config.xsd
<?xml version="1.0"?>
<!--
	Copyright 2005-2006 The Apache Software Foundation
	
	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at
	
	http://www.apache.org/licenses/LICENSE-2.0
	
	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://portals.apache.org/pluto/xsd/pluto-portal-driver-config.xsd"
	elementFormDefault="qualified">

	<xs:element name="pluto-portal-driver">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="portal-name" type="xs:string"
					default="pluto-portal-driver" />
				<xs:element name="portal-version" type="xs:string" />
				<xs:element name="container-name" type="xs:string" />

				<xs:element name="supports">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="portlet-mode"
								type="xs:string" minOccurs="1" maxOccurs="unbounded" />
							<xs:element name="window-state"
								type="xs:string" minOccurs="1" maxOccurs="unbounded" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="portlet-app" minOccurs="1"
					maxOccurs="unbounded">
					<xs:complexType>

						<xs:sequence>
							<xs:element name="context-path">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern
											value="/[a-zA-Z0-9_ /]*" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>

							<xs:element name="portlets">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="portlet"
											minOccurs="1" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute
													name="name" type="xs:string" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>

						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="render-config">
					<xs:complexType>

						<xs:sequence>
							<xs:element name="page" minOccurs="1"
								maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="portlet"
											minOccurs="1" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute
													name="context" type="xs:string" />
												<xs:attribute
													name="name" type="xs:string" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name"
										type="xs:string" />
									<xs:attribute name="uri"
										type="xs:string" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="default" type="xs:string" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== apache/pluto/pluto-portal/src/main/webapp/WEB-INF/pluto-portal-driver-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright 2004 The Apache Software Foundation.
Licensed  under the  Apache License,  Version 2.0  (the "License");
you may not use  this file  except in  compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed  under the  License is distributed on an "AS IS" BASIS,
WITHOUT  WARRANTIES OR CONDITIONS  OF ANY KIND, either  express  or
implied.

See the License for the specific language governing permissions and
limitations under the License.
-->

<pluto-portal-driver
    xmlns="http://portals.apache.org/pluto/xsd/pluto-portal-driver-config.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://portals.apache.org/pluto/xsd/pluto-portal-driver-config.xsd
                        http://portals.apache.org/pluto/xsd/pluto-portal-driver-config.xsd"
    version="1.1">

  <portal-name>pluto-portal-driver</portal-name>
  <portal-version>1.1.0-beta1</portal-version>
  <container-name>Pluto Portal Driver</container-name>

  <supports>
    <portlet-mode>view</portlet-mode>
    <portlet-mode>edit</portlet-mode>
    <portlet-mode>help</portlet-mode>
    <portlet-mode>config</portlet-mode>

    <window-state>normal</window-state>
    <window-state>maximized</window-state>
    <window-state>minimized</window-state>
  </supports>
  
  <portlet-app>
    <context-path>/pluto</context-path>
    <portlets>
      <portlet name="AboutPortlet"/>
      <portlet name="AdminPortlet"/>
    </portlets>
  </portlet-app>
  
  <portlet-app>
    <context-path>/testsuite</context-path>
    <portlets>
      <portlet name="TestPortlet1"/>
      <portlet name="TestPortlet2"/>
    </portlets>
  </portlet-app>
  
  <!-- Render configuration which defines the portal pages. -->
  <render-config default="Test Page">
    <page name="Test Page" uri="/WEB-INF/themes/pluto-default-theme.jsp">
      <portlet context="/testsuite" name="TestPortlet1"/>
      <portlet context="/testsuite" name="TestPortlet2"/>
    </page>
    <page name="Secondary Page" uri="/WEB-INF/themes/pluto-default-theme.jsp">
      <portlet context="/testsuite" name="TestPortlet1"/>
      <portlet context="/testsuite" name="TestPortlet2"/>
    </page>
    <page name="About Pluto" uri="/WEB-INF/themes/pluto-default-theme.jsp">
      <portlet context="/pluto" name="AboutPortlet"/>
    </page>
    <page name="Pluto Admin" uri="/WEB-INF/themes/pluto-default-theme.jsp">
      <portlet context="/pluto" name="AdminPortlet"/>
    </page>
  </render-config>
  
</pluto-portal-driver>
